Фича "Лента событий"
goloviu/java-filmorate pull request #11
Opened 2024-05-02 16:04 UTC by goloviu

feat: добавить ленту событий
test: добавить тесты для новых методов

2024-05-02 16:28 UTC, anbananova requested changes
все хорошо, можно зарефакторить использование событий ленты

2024-05-02 16:28 UTC, anbananova commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public boolean saveUserFeed(Integer userId, Integer eventTypeId, Integer operationId, Integer entityId) {
не очень читаемы в коде айди operationId , entityId при вызове метода savedUserFeed. мне кажется, было бы более читаемо и нагляднее сделать для этих двух событий свои Entity классы перечислений. а внутри метода savedUserFeed использовать значение перечисление, вроде есть метод в них valueOf().

2024-05-03 09:25 UTC, JuliaOlshevskaia approved these changes
Замечаний нет

2024-05-03 19:00 UTC, anbananova approved these changes
все класс, спасибо

2024-05-03 19:30 UTC, merged