Feature Add common films
goloviu/java-filmorate pull request #12
Opened 2024-05-02 21:52 UTC by Yarikov-MY

2024-05-03 06:41 UTC, anbananova requested changes
все хорошо, можно сделать рефакторинг сортировки в стримах

2024-05-03 06:41 UTC, anbananova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(new FilmLikesComparator())
мне кажется, создание отдельного компаратора излишне. сортировка не такая сложная, чтобы делать для нее отдельный класс. Если нужен обратный порядок сортировки от большего к меньшего, можно использовать sorted.reversed

будет что-то типа такого:
```.sorted(Comparator.comparing(FIlm::getUsersLikes().size()).reversed())```

2024-05-03 06:41 UTC, anbananova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return commonFilms.stream().sorted(new FilmLikesComparator()).collect(Collectors.toList());
то же самое с использованием компаратора

2024-05-03 10:36 UTC, JuliaOlshevskaia commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.isUserExist(userId)) {
Можно добавить еще проверку на существование friendId

2024-05-03 20:08 UTC, Yarikov-MY commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(new FilmLikesComparator())
Поправил

2024-05-03 20:08 UTC, Yarikov-MY commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return commonFilms.stream().sorted(new FilmLikesComparator()).collect(Collectors.toList());
Поправил

2024-05-03 20:08 UTC, Yarikov-MY commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.isUserExist(userId)) {
Поправил

2024-05-03 20:13 UTC, anbananova approved these changes

2024-05-04 07:43 UTC, JuliaOlshevskaia approved these changes

2024-05-05 18:11 UTC, merged