Sprint 1
goloviu/java-filmorate pull request #5
Opened 2024-03-08 21:48 UTC by goloviu

feat: добавить модели данных программы Film и User
feat: реализовать контроллеры для обработки Film и User
feat: добавить валидацию User и Film
feat: создать кастомный ValidationException
test: реализовать тест валидации контроллеров FilmControllerTest UserControllerTest

2024-03-09 18:28 UTC, dgumich requested changes

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addOrUpdateFilm(@Valid @NonNull @RequestBody Film film) {
Не надо делать мультитул=) Для добавления свой метод, для обновления - свой. Удали логику, которая связана с добавлением фильма из этого метода.

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @NonNull @RequestBody Film film) {
@NonNull не нужна

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == null && !films.containsValue(film)) {
Переработай блок if-else:
в if делай проверку film.getId() != null && films.containsValue(film) , если правда - то бросаешь исключение.
В таком случае можешь убрать блок else и просто написать код со строк 29-33. Это поможет уменьшить количество блоков и улучшит читаемость кода.

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен список фильмов");
Не получен список фильмов, а "Получен GET запрос на нахождения всех фильмов". Старайся писать осмысленные вещи в логах, потому что это то, с чем ты часто будешь работать.

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addUser(@Valid @NonNull @RequestBody User user) {
Здесь аналогичные замечания:
1) @NonNull не нужен
2) Переработать блок if-else

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addOrUpdateUser(@Valid @NonNull @RequestBody User user) {
Аналогично:
1) @NonNull не нужен
2) Убрать логику по добавлению пользователя, оставить только обновление

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Зачем сразу @NotBlank и  @NonNull?=) Понимаешь, что одного достаточно, потому что оно более строгое? Можешь более подробно почитать про разницу https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull(message = "Описание фильма не задано(null)")
Тут аж два раза @NotNull. Надо быть внимательным=)

2024-03-09 18:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "email пользователя не должен быть пустой, состоять из пробелов или неопределяться(null)")
Нам не нужны три аннотации, достаточно одной)

2024-03-10 15:58 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addOrUpdateFilm(@Valid @NonNull @RequestBody Film film) {
Исправлено
А почему мы не можем использовать PUT для добавления и обновления, ведь он для этого и нужен?

2024-03-10 16:59 UTC, goloviu reviewed
Дмитрий, спасибо за замечания, по указанным недочетам внес правки в код!

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @NonNull @RequestBody Film film) {
Исправлено

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == null && !films.containsValue(film)) {
Спасибо за замечание, так и правда лучше выглядит
Исправлено

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен список фильмов");
Я включил логирование эндпоинтов через спринг, вот так выглядит: 
![image](https://github.com/goloviu/java-filmorate/assets/147878926/b20b912b-dd25-4b58-b4e1-c00c430a8fcb)
Такое решение не совсем удачное?
Исправлено

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addUser(@Valid @NonNull @RequestBody User user) {
Исправлено

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addOrUpdateUser(@Valid @NonNull @RequestBody User user) {
Исправлено

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Забыл убрать когда добавил контруктор по умолчанию от lombok и конструктор со всеми аргументами, исправлено! 
Изначально оставил т.к lombok с контруктором requiredArgsConstructor принимает final поля или nonnull

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull(message = "Описание фильма не задано(null)")
Исправлено

2024-03-10 16:59 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "email пользователя не должен быть пустой, состоять из пробелов или неопределяться(null)")
Частично исправлено
Тут не понял немного как можно через 1 аннотацию реализовать, по условию требуется чтобы не было пустой и содержало символ @, поэтому
оставил NotBlank и Email

2024-03-11 01:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addOrUpdateFilm(@Valid @NonNull @RequestBody Film film) {
Тогда зачем тебе метод POST? Шли все на PUT. Дублирование логики. Да, бывают такие случаи, когда обновляет или создает. Но здесь так лучше не делать, для каждой операции - свой апи.

2024-03-11 01:41 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "email пользователя не должен быть пустой, состоять из пробелов или неопределяться(null)")
Тогда такой вопрос: если ты передаешь строку, которая blank, что вернет @Email? Правильно, ошибку валидации. Так как не содержит символ @. Получается, что NotBlank не нужно, если пришлешь пустую строку, Email все равно ее не пропустит, потому что имеет более строгое требование. Кстати, по поводу символа @. Советую почитать документацию к @Email и посмотреть какой дефолтный паттерн он обрабатывает=) Ну и исправить после этого, как надо=)

2024-03-11 01:43 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен список фильмов");
debug очень низкий уровень логгирования и чаще всего используется только во время тестов/отладки приложения. На проде у тебя уровня debug не будет, просто потому, что ты потонешь в логах. Ну и наличие спринговских логов не освобождает тебя от ответственности логгировать осмысленное сообщение=)

2024-03-11 01:46 UTC, dgumich requested changes

2024-03-11 01:46 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private HashMap<Integer, Film> films = new HashMap<>();
Старайся делать поля final или final static где это возможно. Тут, например, можно так сделать.

2024-03-11 01:46 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() != null && films.containsValue(film)) {
Отлично, можно сделать еще лучше и вынести в отдельный метод. Тогда код станет еще чище, и дублирование станет меньше=)

2024-03-11 01:46 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() != null && users.containsValue(user)) {
Аналогично, вынеси в отдельный метод

2024-03-11 15:20 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private HashMap<Integer, Film> films = new HashMap<>();
Исправлено

2024-03-11 15:27 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() != null && films.containsValue(film)) {
Сделано

2024-03-11 15:27 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() != null && users.containsValue(user)) {
Сделано

2024-03-11 20:12 UTC, merged