feat: Реализовать добавление и удаление из друзей пользователей
goloviu/java-filmorate pull request #6
Opened 2024-03-20 22:24 UTC by goloviu

feat: Реализовать нахождение общих друзей у двоих пользователей
feat: Добавить возможность ставить лайки фильмам от пользователей
feat: Добавить функцию возврата популярных фильмов, отфильтрованных по лайкам
feat: Кастомные исключение и обработка исключений Спрингом в filmorate.exceptionhandler.ErrorHandler
feat: Реализовать локальную базу данных в программе InMemoryFilmStorage InMemoryUserStorage
refactor: Разделить базу данных, бизнес-логику, контроллерны по разным пакетам

2024-03-21 22:18 UTC, dgumich requested changes

2024-03-21 22:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(defaultValue = "10") Integer count) {
Молодец, что разобрался с дефолт велью

2024-03-22 13:47 UTC, goloviu reviewed
Все замечания были учтены и исправлены!

2024-03-22 13:47 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final LocalDate FIRST_FILM_DATE = LocalDate.parse("1895-12-28");
Спасибо за уточнение и ценную информацию!
Исправлено

2024-03-22 13:47 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Исправлено

2024-03-22 13:47 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        InMemoryFilmStorage films = (InMemoryFilmStorage) filmStorage;
Исправлено

2024-03-22 13:47 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        InMemoryFilmStorage films = (InMemoryFilmStorage) filmStorage;
Исправлено

2024-03-22 13:47 UTC, goloviu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        InMemoryFilmStorage films = (InMemoryFilmStorage) filmStorage;
По ТЗ немного запутался, думал требуется определить только 3 основных метода в интерфейсе (Добавление, обновление, удаление)

2024-03-23 14:02 UTC, dgumich approved these changes

2024-03-23 14:02 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final LocalDate FIRST_FILM_DATE = LocalDate.parse("1895-12-28");
Советую прочитать все правила=) Там не так много https://www.oracle.com/java/technologies/javase/codeconventions-contents.html

2024-03-23 14:02 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        InMemoryFilmStorage films = (InMemoryFilmStorage) filmStorage;
Понял, если есть вопросы по ТЗ - задавай уточняющие вопросы наставнику

2024-03-23 20:26 UTC, merged