Add database
goloviu/java-filmorate pull request #8
Opened 2024-04-12 17:34 UTC by goloviu

2024-04-13 18:57 UTC, dgumich requested changes

2024-04-13 18:57 UTC, dgumich commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar,email varchar NOT NULL UNIQUE,login varchar NOT NULL UNIQUE,birthday date NOT NULL)
Да, компактно, но не читаемо=)
Не поленись и напиши с новой строчки каждый столбец.
Кроме того для varchar укажи количество символов, сколько должно быть (varchar(10) или varchar(129))

2024-04-15 20:29 UTC, goloviu commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar,email varchar NOT NULL UNIQUE,login varchar NOT NULL UNIQUE,birthday date NOT NULL)
Исправлено

2024-04-16 16:20 UTC, dgumich approved these changes

2024-04-16 16:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exceptionhandler/ErrorHandler.java
> +    public ErrorResponse userNotFoundHandle(final Throwable exception) {
Обычно пытаются сузить тип параметра как могут. Throwable слишком общий. Хотя бы до RunTimeException

2024-04-16 16:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +@Component("userDbStorage")
Молодец, что даешь название бину. Хотя, спринг по умолчанию даст точно такое же, на некоторых проектах это делают в любом случае.

2024-04-19 18:21 UTC, merged